# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MayoDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Moya', '~> 13.0'
  # Pods for MayoDemo

  target 'MayoDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MayoDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
